version: "3.7"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    command: sh -c "poetry run gunicorn -w 4 main:app --bind 0.0.0.0:8000"
    volumes:
      - data:/usr/src/app
    restart: unless-stopped



volumes:
  data:
